# This is a basic workflow to help you get started with Actions

name: RPM Build

# Controls when the action will run. Triggers the workflow on push 
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install Prerequisites
      run: dnf install -y rpmdevtools dnf-utils spectool dnf-utils && dnf clean all

    - name: Creat RPM Dir Structure
      run: rpmdev-setuptree

    - name: Install Dependencies
      run: sudo yum-builddep --assumeyes cello.spec

    - name: Create source tarball
      run: mkdir cello-1.0.2; tar czf SOURCES/cello-1.0.2.tar.gz cello-1.0.2

    - name: Build RPM
      run: rpmbuild --define '_topdir /github/workspace' -ba cello.spec

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: Binary RPM
        # Directory containing files to upload
        path: ${{ steps.rpm.outputs.rpm_dir_path }}
